import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';

import { ReactQueryClientProvider } from "./components/providers/reactquery";
import {ColorSchemeScript, MantineProvider, mantineHtmlProps} from '@mantine/core'




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
    <html lang="en" {...mantineHtmlProps}>
      <head><ColorSchemeScript/></head>
      <body
      
      >
       <MantineProvider> {children}</MantineProvider>
      </body>
    </html>
    </ReactQueryClientProvider>
  );
}
